### ISSUE TITLE
Dtypes bug with h5py v3+

### ISSUE THREAD

**Issue by Sinclert** [diana-hep/madminer#446]
This issue describes the found incompatibilities when using [h5py v3.0.0+](https://github.com/h5py/h5py/releases/tag/3.0.0) (a version published on 10/31/2020).

### Context
Madminer does **not specify any h5py version** on its [setup.py](https://github.com/diana-hep/madminer/blob/master/setup.py) file, which, until very recently, resolved in `v2.10.0`. With the jump to h5py `v3.0.0` there are some breaking changes that affect this package directly.

### Possible solutions:
A) Investigate the list of [breaking changes](https://docs.h5py.org/en/latest/whatsnew/3.0.html#breaking-changes-deprecations), and figure out how to adapt the code **[recommended]**.
B) Define h5py version `2.10.0` as an upper limit within the [setup.py](https://github.com/diana-hep/madminer/blob/master/setup.py).

### Bug encountered:
I encountered h5py `v3.0.0` incompatibilities when running the [Scailfin/madminer-workflow-ml](https://github.com/scailfin/madminer-workflow-ml) with the latest madminer version (`v0.7.5`).

#### Steps to reproduce:
1. Launch Docker locally.
2. Run the sub-workflow locally:
```shell script
git clone https://github.com/scailfin/madminer-workflow-ml.git
cd madminer-workflow-ml
git checkout ratio-estimator-selection
make yadage-run
```

#### Error trace:
```
Traceback (most recent call last):
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/code/sampling.py", line 90, in <module>
    test_split=test_split,
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/madminer/sampling/sampleaugmenter.py", line 636, in sample_train_ratio
    double_precision=double_precision,
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/madminer/sampling/sampleaugmenter.py", line 1420, in _sample
    double_precision=double_precision,
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/madminer/sampling/sampleaugmenter.py", line 1593, in _sample_set
    generated_close_to=None if not sample_only_from_closest_benchmark else theta_value_sampling,
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/madminer/analysis/dataanalyzer.py", line 151, in event_loader
    return_sampling_ids=return_sampling_ids,
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/madminer/utils/interfaces/madminer_hdf5.py", line 234, in madminer_event_loader
    this_weights = np.array(weights[current:this_end, benchmark_filter])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 774, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/Users/sinclert/Documents/Repos/GitHub/Scailfin/madminer-workflow-ml/venv/lib/python3.7/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 269, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 180, in h5py._selector.Selector.apply_args
TypeError: Indexing arrays must have integer dtypes
```

**Comment by johannbrehmer** [comment]
Hi Sinclert,

Thanks a lot for opening this. I encountered the same issue the other day and fixed it on the `finite-differences` branch -- sorry, I should have fixed it everywhere immediately! I'll do that soon.

Cheers,
Johann

**Comment by Sinclert** [comment]
Great to hear.

Thanks Johann
